// Generated by gencpp from file service_basic/service1Response.msg
// DO NOT EDIT!


#ifndef SERVICE_BASIC_MESSAGE_SERVICE1RESPONSE_H
#define SERVICE_BASIC_MESSAGE_SERVICE1RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_basic
{
template <class ContainerAllocator>
struct service1Response_
{
  typedef service1Response_<ContainerAllocator> Type;

  service1Response_()
    : result(0)  {
    }
  service1Response_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int64_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::service_basic::service1Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_basic::service1Response_<ContainerAllocator> const> ConstPtr;

}; // struct service1Response_

typedef ::service_basic::service1Response_<std::allocator<void> > service1Response;

typedef boost::shared_ptr< ::service_basic::service1Response > service1ResponsePtr;
typedef boost::shared_ptr< ::service_basic::service1Response const> service1ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_basic::service1Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_basic::service1Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace service_basic

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::service_basic::service1Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_basic::service1Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_basic::service1Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_basic::service1Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_basic::service1Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_basic::service1Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_basic::service1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::service_basic::service1Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::service_basic::service1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_basic/service1Response";
  }

  static const char* value(const ::service_basic::service1Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_basic::service1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 result\n\
\n\
";
  }

  static const char* value(const ::service_basic::service1Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_basic::service1Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct service1Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_basic::service1Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_basic::service1Response_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_BASIC_MESSAGE_SERVICE1RESPONSE_H
