// Generated by gencpp from file service_basic/service1.msg
// DO NOT EDIT!


#ifndef SERVICE_BASIC_MESSAGE_SERVICE1_H
#define SERVICE_BASIC_MESSAGE_SERVICE1_H

#include <ros/service_traits.h>


#include <service_basic/service1Request.h>
#include <service_basic/service1Response.h>


namespace service_basic
{

struct service1
{

typedef service1Request Request;
typedef service1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct service1
} // namespace service_basic


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_basic::service1 > {
  static const char* value()
  {
    return "d431cae597499d244ef1c576e21358c8";
  }

  static const char* value(const ::service_basic::service1&) { return value(); }
};

template<>
struct DataType< ::service_basic::service1 > {
  static const char* value()
  {
    return "service_basic/service1";
  }

  static const char* value(const ::service_basic::service1&) { return value(); }
};


// service_traits::MD5Sum< ::service_basic::service1Request> should match 
// service_traits::MD5Sum< ::service_basic::service1 > 
template<>
struct MD5Sum< ::service_basic::service1Request>
{
  static const char* value()
  {
    return MD5Sum< ::service_basic::service1 >::value();
  }
  static const char* value(const ::service_basic::service1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_basic::service1Request> should match 
// service_traits::DataType< ::service_basic::service1 > 
template<>
struct DataType< ::service_basic::service1Request>
{
  static const char* value()
  {
    return DataType< ::service_basic::service1 >::value();
  }
  static const char* value(const ::service_basic::service1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_basic::service1Response> should match 
// service_traits::MD5Sum< ::service_basic::service1 > 
template<>
struct MD5Sum< ::service_basic::service1Response>
{
  static const char* value()
  {
    return MD5Sum< ::service_basic::service1 >::value();
  }
  static const char* value(const ::service_basic::service1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_basic::service1Response> should match 
// service_traits::DataType< ::service_basic::service1 > 
template<>
struct DataType< ::service_basic::service1Response>
{
  static const char* value()
  {
    return DataType< ::service_basic::service1 >::value();
  }
  static const char* value(const ::service_basic::service1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_BASIC_MESSAGE_SERVICE1_H
